// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgvnlkoqyriwsjrdxbks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtndm5sa29xeXJpd3NqcmR4YmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjM5MDAsImV4cCI6MjA2NTUzOTkwMH0.2K66sO4b89dy6onNlJXEqfQT99k8JbP7uAHPto5T99A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);